In [ ]:
# maman 11 deep learning
import torch

# Question a
# Return tensor A after boardcasting to B.
def my_expand(A,B):
  C = B.clone()
  try:
    C += A-B
  except Exception as e:
    raise (e)
    return
  return C

# Question b
# Check if two tensors can broadcast together. If true, returns the broadcast size. 
def is_broadcastable(A,B):
  i = 1
  D = [] # dimentions of the returning tensor
  while i < 1+min(len(A.size()),len(B.size())):
    tempA = A.size()[-i]
    tempB = B.size()[-i]
    # check if boardcast is valid
    if tempA == tempB or tempA == 1 or tempB == 1:
      i += 1
      # update returning dimentions
      D.append(max(tempA,tempB))
    else:
      return False;
  # complete dimentions according to the longer tensor
  longer = A
  if len(A.size()) < len(B.size()):
    longer = B
  while i < 1+max(len(A.size()),len(B.size())):
    D.append(longer.size()[-i])
    i += 1
  return True,D[::-1]

# Question c
# Return two tensors after broadcasting them together 
def my_broadcast(A,B):
  if is_broadcastable(A,B) == False:
    raise Exception("Two given tensors cannot broadcast together")
  C = torch.zeros((is_broadcastable(A,B)[1]))
  D = C.clone()
  return my_expand(A,C),my_expand(B,D)




# Question d
# Test all previous functions
A1 = torch.arange(3)
B1 = torch.arange(9).reshape(3,3)
A2 = torch.arange(4).view(1,4)
B2 = torch.arange(4).view(4, 1)
A3 = torch.arange(12).view(1,3, 4,1)
B3 = torch.arange(8).view(1, 4,2)  
A4 = torch.arange(16).reshape(4,4)
B4 = torch.arange(80).reshape(5,4,4)
A5 = torch.arange(15).reshape(3,5)
B5 = torch.arange(24).reshape(2,2,3,2)
A6 = torch.arange(100).reshape(10,1,10)
B6 = torch.arange(100).reshape(10,5,2)
A = [A1,A2,A3,A4,A5,A6]
B = [B1,B2,B3,B4,B5,B6]
index = 1
for a,b in zip(A,B):
  print(index)
  index += 1 
  if is_broadcastable(a,b) == False:
    print("Can't broadcast together")
  # expand
  try:
    x = my_expand(a,b)
    y = a.expand_as(b)
    print("expand: both functions approved")
    z = x==y
    print(z)
  except:
    # check if valid accordingto pytorch
    try:
       y = a.expand_as(b)
       print("expand: work in pytorch but not in my func!!!!")
    except:
      print("expand: both functions throws exception")
  # broadcast
  try:
    c,d = my_broadcast(a,b)
    e,f = torch.broadcast_tensors(a,b)
    print("broadcast: both functions approved")
    g = c == e
    h = d == f
    print(g,h,sep = '\n')
  except:
    try:
      torch.broadcast_tensors(a,b)
      print("broadcast: work in pytorch but not in my func!!!!")
    except:
      print("broadcast: both functions throws exception")

1
expand: both functions approved
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
broadcast: both functions approved
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
2
expand: both functions throws exception
broadcast: both functions approved
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
3
expand: both functions throws exception
broadcast: both functions approved
tensor([[[[True, True],
          [True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
    

In [ ]:
'''
  output:

  1
expand: both functions approved
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
broadcast: both functions approved
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
2
expand: both functions throws exception
broadcast: both functions approved
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
3
expand: both functions throws exception
broadcast: both functions approved
tensor([[[[True, True],
          [True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True],
          [True, True]]]])
tensor([[[[True, True],
          [True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True],
          [True, True]]]])
4
expand: both functions approved
tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])
broadcast: both functions approved
tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])
tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])
5
Can't broadcast together
expand: both functions throws exception
broadcast: both functions throws exception
6
Can't broadcast together
expand: both functions throws exception
broadcast: both functions throws exception

'''

"\n  output:\n\n  1\nexpand: both functions approved\ntensor([[True, True, True],\n        [True, True, True],\n        [True, True, True]])\nbroadcast: both functions approved\ntensor([[True, True, True],\n        [True, True, True],\n        [True, True, True]])\ntensor([[True, True, True],\n        [True, True, True],\n        [True, True, True]])\n2\nexpand: both functions throws exception\nbroadcast: both functions approved\ntensor([[True, True, True, True],\n        [True, True, True, True],\n        [True, True, True, True],\n        [True, True, True, True]])\ntensor([[True, True, True, True],\n        [True, True, True, True],\n        [True, True, True, True],\n        [True, True, True, True]])\n3\nexpand: both functions throws exception\nbroadcast: both functions approved\ntensor([[[[True, True],\n          [True, True],\n          [True, True],\n          [True, True]],\n\n         [[True, True],\n          [True, True],\n          [True, True],\n          [True, True]],\n